.mode	columns
.headers	on
.nullvalue	NULL

 CREATE VIEW VALORES_VIEW AS
SELECT (SELECT 
sum  (CASE WHEN Medico IS NOT NULL THEN 1 ELSE 0 END)) med,
(sum  (CASE WHEN Enfermeiro IS NOT NULL THEN 1 ELSE 0 END)) enf,
(sum  (CASE WHEN Tecnico IS NOT NULL THEN 1 ELSE 0 END)) tec
FROM Exame;
SELECT CASE WHEN (SELECT MIN(med) FROM VALORES_VIEW) > (SELECT MIN(enf) FROM VALORES_VIEW ) AND
(SELECT MIN(med) FROM VALORES_VIEW) > (SELECT MIN(tec) FROM VALORES_VIEW )
 THEN (SELECT "São os Médicos") END;
 SELECT CASE WHEN (SELECT MIN(enf) FROM VALORES_VIEW) > (SELECT MIN(med) FROM VALORES_VIEW ) AND
(SELECT MIN(enf) FROM VALORES_VIEW) > (SELECT MIN(tec) FROM VALORES_VIEW )
 THEN (SELECT "São os Enfermeiros") END;
 SELECT CASE WHEN (SELECT MIN(tec) FROM VALORES_VIEW) > (SELECT MIN(med) FROM VALORES_VIEW ) AND
(SELECT MIN(tec) FROM VALORES_VIEW) > (SELECT MIN(enf) FROM VALORES_VIEW )
 THEN (SELECT "São os Técnicos") END;